### ISSUE TITLE
Support Multiple IFormFile

### ISSUE THREAD

**Issue by badreddine-dlaila** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#1]
Hello, 

Excellent job done with this library.
Is there any chance that you add support for multiple files upload ?

```csharp
public class MyWrapper
    {
        [FromJson]
        public Product Product { get; set; }

        public IEnumerable<IFormFile> File { get; set; } // <-- That would be awesome if we could do this
    }

    public class Product
    {
        public string Name { get; set; }

        public ProductType Type { get; set; }
    }

    public enum ProductType
    {
        Phone,
        Laptop
    }
```
Actual behavior when doing as above :
 
![image](https://user-images.githubusercontent.com/4688209/80915185-eb221180-8d50-11ea-8918-3fa4a2e6d555.png)

**Comment by Morasiu** [comment]
Thanks!

I'll check Open API specs and Swagger Docs specs and let you know!

**Comment by Morasiu** [comment]
I've done a little research and it's a problem with Swagger UI.

[Here](https://github.com/swagger-api/swagger-ui/issues/4600) is related issue. Also [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1029) is an issue from Swashbuckle.AspNetCore.

**Comment by Morasiu** [comment]
Solved in the new swagger version
