### ISSUE TITLE
Problem with validating GUID

### ISSUE THREAD

**Issue by e1imba** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#10]
Hello, 

First of all, well done for this library.
It is simple, very useful and has saved me a lot of time.

I have one small problem that would be good if I could cover.
My model for JSON file consist GUID property. I have my own custom written validator **[ValidGuid]** which will detect if someone send valid GUID or not.

![image](https://user-images.githubusercontent.com/44132041/139440134-fef09ea5-57a4-49ea-a65a-a61c004ba2e4.png)

This is my controller.

![image](https://user-images.githubusercontent.com/44132041/139440035-750bb9dd-48f9-4608-a544-19076817a36e.png)

Problem is, that validator is not working if someone send invalid Guid. **`{ "customerId": " ", "name": "Ivan"}`**

This is an error. 

![image](https://user-images.githubusercontent.com/44132041/139441064-b4bc1c38-b1cf-4b0d-8177-98e6edfc1f22.png)

If I change **CustomerId** type to **string** it is working, but I would like to use it as Guid if it is possible.

**Comment by Morasiu** [comment]
Hi, thanks for that issue. I'll look it up. Can you share your Validator?

**Comment by e1imba** [comment]
Ofc, it is just basic validation check 

![image](https://user-images.githubusercontent.com/44132041/139643289-521241b0-48c3-4f7f-9201-bee532625de8.png)

**Comment by Morasiu** [comment]
Locally I've changed the JSON binding so when some deserialization fails it returns 400 with an error like that:

![image](https://user-images.githubusercontent.com/19236279/139654005-6339930a-d6eb-4041-8044-bcc4b654a071.png)

Unfortunately binding is applied before any validation, so I cannot respect any validation attributes. 

Did something like this solve your problem?

**Comment by e1imba** [comment]
Yes of course, just not to throw 500 Internal server error. Thank you so much! :)

**Comment by Morasiu** [comment]
Fixed in v.1.6.1 :)
