### ISSUE TITLE
Need .NET 6 support

### ISSUE THREAD

**Issue by CelerityChip** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#11]
This package is absolutely wonderful, everything I needed in one place.

Can you please get a .NET 6 version of the package (with Swagger package updates) out there? I get method not found exceptions including this from a .NET 6 assembly. Cloning locally, changing the target framework, and updating the Swagger packages was all that was necessary for my solution.

Thank you!

**Comment by Morasiu** [comment]
Thanks! Will do

**Comment by minorityuk** [comment]
@Morasiu No problem, great project and I just upgraded my project to .net 6 and experienced the issue and needed to correct it so thought i save you the time.
