### ISSUE TITLE
MultipartFormData<JsonElement> causes NullReferenceException

### ISSUE THREAD

**Issue by tomaszoida** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#14]
Using an entityWrapper typed with JsonElement
```[FromForm] MultipartFormData<JsonElement> entityWrapper```
generates the following error:
NullReferenceException: Object reference not set to an instance of an object.
Swashbuckle.AspNetCore.JsonMultipartFormDataSupport.Integrations.MultiPartJsonOperationFilter.GetSchema(OperationFilterContext context, PropertyInfo propertyInfo)
Swashbuckle.AspNetCore.JsonMultipartFormDataSupport.Integrations.MultiPartJsonOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)

**Comment by Morasiu** [comment]
I'll check this

**Comment by tomaszoida** [comment]
@Morasiu, did you have a chance to take a look at that issue? 
Thanks!

**Comment by Morasiu** [comment]
Yeah. Not yet. Sadly I'll be busy for two upcoming weeks. I think I has to wait... Or you can make a PR yourself! :D

**Comment by Morasiu** [comment]
Finally fixed in 1.7.1 :)
