### ISSUE TITLE
Json is null if model was serialized as JavaScript Blob

### ISSUE THREAD

**Issue by phunanon** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#16]
Hello,

Firstly, thank you for this nuget package, it really simplifies this very particular case with Swashbuckle and fixes our swagger file perfectly!

We use https://openapi-generator.tech/ to generate our TypeScript API (using the typescript-axios generator). It generates this code here:

```ts
localVarFormParams.append('Json', new Blob([JSON.stringify(json)], { type: "application/json", }));
```

Which as an example contributes to a request like this:

```
-----------------------------45968866839125028722676728444
Content-Disposition: form-data; name="Json"; filename="blob"
Content-Type: application/json

{"elections":["4514da4b-2a31-491d-9810-fd1fd391f054"],"isWeighted":true,"name":"uvcs"}
-----------------------------45968866839125028722676728444
Content-Disposition: form-data; name="File"; filename="uvcs.csv"
Content-Type: application/vnd.ms-excel

... some file content ...

-----------------------------45968866839125028722676728444--
```

However, when this is consumed via MultipartFormData the Json property is null.

If instead it was generated this way...

```ts
localVarFormParams.append('Json', JSON.stringify(json));
```

The request is sent as

```
-----------------------------213525737619726063793723859368
Content-Disposition: form-data; name="Json"

{"elections":["4514da4b-2a31-491d-9810-fd1fd391f054"],"isWeighted":true,"name":"uvcs"}
... more ...
```

And this is consumed by MultipartFormData correctly.

I could try and figure out how to wrangle the generator in such a way that it doesn't try to serialise it as a blob, but I'm opening an issue here as perhaps forgiving the inclusion of `filename` and `Content-Type` for JSON is within the interest of this package?

Thank you for your time!

**Comment by stiio** [comment]
@phunanon Also faced with this problem. I made [fork](https://github.com/stiio/JsonMultipartFormDataSupport) that solves this problem and published a NuGet package.

**Comment by Morasiu** [comment]
Sounds good. Can you just make a PR and we can try to merge it?

**Comment by Morasiu** [comment]
Added in 1.8.0. Thanks @stiio!
