### ISSUE TITLE
Projects targeting netcoreapp3.x should use AspNetCore 3.x as well

### ISSUE THREAD

**Issue by psaxton** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#2]
Attempting to build a netcoreapp3.1 project targeting AspNetCore 3.1 causes build errors because Swashbuckle.AspNetCore.JsonMultipartFormDataSupport is targeting AspNetCore 2.2.

**Comment by Morasiu** [comment]
Thanks for issue.

Oh... I think it works in my home project. I'll check it!

**Comment by psaxton** [comment]
I'm preparing a PR right now for it -- Didn't expect such a quick response.

**Comment by psaxton** [comment]
Pull Request #3 is ready for you to review. Thank you.

**Comment by Morasiu** [comment]
Great. I'll merge it tomorrow and release a new version on Nuget 👍
