### ISSUE TITLE
Multiple Fromjson Attributes Exception

### ISSUE THREAD

**Issue by ArcKos00** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#20]
When I try to create a wrap model with multiple FromJson properties, an error occurs.

![image](https://github.com/user-attachments/assets/e6b95995-1474-47da-9213-77acece6b4dd)
![image](https://github.com/user-attachments/assets/6d1bf2e4-ad3f-458f-8fa9-4d291a637451)

I know how to fix it, so I'll create an issue and pull request.

**Comment by Morasiu** [comment]
Sure :)

**Comment by Morasiu** [comment]
Added in 1.10.0. Thanks!
