### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by npfernandeztheillet** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#6]
Hello, please update readme because in the last version you need to provide jsonSerializerChoice to the extension method:
i.e.
services.AddJsonMultipartFormDataSupport(JsonSerializerChoice.Newtonsoft);

**Comment by Morasiu** [comment]
My bad. I'll do that. Thanks!

**Comment by Morasiu** [comment]
Thanks for fixing README
