### ISSUE TITLE
SwaggerGen Version 6> Issue

### ISSUE THREAD

**Issue by npfernandeztheillet** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#7]
Hey! me again!
If you use SwaggerGen version 6 or greater than 6 you will receive this error:
MissingMethodException: Method not found: 'Boolean Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.TryGetIdFor(System.Type, System.String ByRef)'.

I downloaded your repo and update versions of all the packages excepts filters and used TryLookupByType instead TryGetIdFor. 
Here is the change that at least works:

/// <summary>
		/// Generate schema for propertyInfo
		/// </summary>
		/// <returns></returns>
		private OpenApiSchema GetSchema(OperationFilterContext context, PropertyInfo propertyInfo) {
			bool present = context.SchemaRepository.TryLookupByType(propertyInfo.PropertyType, out OpenApiSchema openApiSchema);
			if (!present)
			{
				_ = context.SchemaGenerator.GenerateSchema(propertyInfo.PropertyType, context.SchemaRepository);
				_ = context.SchemaRepository.TryLookupByType(propertyInfo.PropertyType, out openApiSchema);
				var schema = context.SchemaRepository.Schemas[openApiSchema.Reference.Id];
				AddDescription(schema, openApiSchema.Title);
				AddExample(propertyInfo, schema);
			}
			return context.SchemaRepository.Schemas[openApiSchema.Reference.Id];
		}

**Comment by Morasiu** [comment]
Great. You can make a PR with it ❤️

**Comment by Morasiu** [comment]
Fixed in PR. Thanks @npfernandeztheillet
