### ISSUE TITLE
Imcompatible parameter in SwaggerGen

### ISSUE THREAD

**Issue by npfernandeztheillet** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#8]
Hello, me again!

If you use this option DescribeAllParametersInCamelCase() in?
services.AddSwaggerGen(o => {
				o.SwaggerDoc("v1", new OpenApiInfo {
					Title = "Demo",
					Version = "v1"
				});
				o.DescribeAllParametersInCamelCase();
			});
then the functionality doesn't work.
Change to lowercase properties is a workaround, but I don't know if it's the best!

**Comment by Morasiu** [comment]
Sounds like a hack. It should be easier to make

**Comment by Morasiu** [comment]
Fixed in 1.6.0 :)
